export const CART_ON_REQUEST = "CART_ON_REQUEST";
export const CART_INIT = "CART_INIT";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_TO_CART";
export const CLEAN_CART = "CLEAN_CART";
export const INCREASE_PRODUCT_QUANTITY = "INCREASE_PRODUCT_QUANTITY";
export const DECRASE_PRODUCT_QUANTITY = "DECREASE_PRODUCT_QUANTITY";
